import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import { languages } from '../../platform/i18n/settings';
import '../../platform/globals.css';
import Providers from './providers';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <Providers lang={lng}>{children}</Providers>
      </body>
    </html>
  );
}
